### PR TITLE
feat: support for modifier

### PR DESCRIPTION
**Pull request by ota-meshi**
I was working on an experimental implementation of the [RegExp Modifiers]. I'm not sure yet if this implementation can be merged as-is, but I'm opening a PR to share my AST ideas as well.

[RegExp Modifiers]: https://github.com/tc39/proposal-regexp-modifiers
https://github.com/tc39/proposal-regexp-modifiers

### CODE REVIEW

**Comment by RunDevelopment** [comment]
A bit of feedback from my first impression of the AST (I haven't looked at the parser implementation yet):

1. `Group#modifiers: Modifiers | null`: When is `modifiers` null? Is it null when modifiers are impossible (legacy regexes) or when there are no modifiers (e.g. `/(?:foo)/u`)? What about `/(?-:foo)/u`?
2. `Modifiers#add` and `Modifiers#remove`: What does `null` mean for them? Can both be `null`? If `null` means "no flags", then why not have a `ModifierFlags` with all flags set to false?

**Comment by ota-meshi** [comment]
Thank you for your comment!

> Group#modifiers: Modifiers | null: When is modifiers null? Is it null when modifiers are impossible (legacy regexes) or when there are no modifiers (e.g. /(?:foo)/u)? What about /(?-:foo)/u?

Regexps without modifiers will be `null`. For example, `modifiers` of `(?:x)` is null. `(?-:x)` will result in a parsing error.

> Modifiers#add and Modifiers#remove: What does null mean for them? Can both be null? If null means "no flags", then why not have a ModifierFlags with all flags set to false?

I thought that nodes with no width should be avoided, but after re-checking it, it seems that nodes with no width already exist among the nodes generated by `regexpp`. For example, a `Flags` node without flags has no width.
For consistency, it seems necessary to set a `ModifierFlags` node that sets all flags to false, as you say. I will make that change later.

**Comment by RunDevelopment** [comment]
> Regexps without modifiers will be `null`. For example, `modifiers` of `(?:x)` is null.

I see, makes sense.

> `(?-:x)` will result in a [parsing error](https://tc39.es/proposal-regexp-modifiers/#sec-patterns-static-semantics-early-errors).

Ah, my bad. I only looked at the grammar itself and not its early errors.

**Review by MichaelDeBoey — APPROVED** [review]

**Review by MichaelDeBoey — APPROVED** [review]

**Comment by ota-meshi** [comment]
Thank you for reviewing this PR.
The PR I opened for Acorn was also merged, so this one should be fine too. I will merge this PR.

**Pull request merged**
