### PR TITLE
✨ add parents to regexp visitor

### PR DESCRIPTION
**Pull request by connor4312**
Duplicating https://github.com/mysticatea/regexpp/pull/18

### CODE REVIEW

**Review by MichaelDeBoey — CHANGES_REQUESTED** [review]
@connor4312 Please rebase your branch onto latest `main` & resolve conflicts

**Comment by RunDevelopment** [comment]
Cool PR!

Question: Is it intentional that the parents array does not include the parents of the root node (= the node we call `RegExpVisitor#visit` on)? This seems strange to me, because it means that `parents` does not contain all ancestors of a node. In other words, I assumed `!currentNode.parent || currentNode.parent == parents.at(-1)` to be an invariant.

About the name "parents": a parent is typically the first direct ancestor of a node. So maybe we should name the parameter `ancestors`? I'm not sure which one is better, though.

Also, maybe we could do that better than `Node[]` for the type of `parents`? E.g. we know that the `parents` array of a `Pattern` node can only contain a `RegExpLiteral` node, and we know that the `parents` array of a quantifier can't contain a `Character` node. I think it would be nice if we had e.g. `onGroupEnter?(node: Group, parents: readonly Ancestor<Group>[]): void` (using [the `Ancestor` type from here](https://github.com/RunDevelopment/regexp-ast-analysis/blob/master/src/basic.ts#L268) in this example).
I think this would make it easier for people to use the `parents` array, since TS has a better idea about its contents.

**Comment by ota-meshi** [comment]
I don't think we need to add this parameter.
You can already easily access the parent node using `node.parent`.
What use cases are new `parents` useful for?

**Comment by connor4312** [comment]
ah, you're right. Somehow missed that however many years ago I wrote this.

**Pull request closed without merging**
