### PR TITLE
feat: add support v flag

### LINKED ISSUE #80: Support for `v` flag and properties of strings
I wanted to ask whether there are plans to support [the `v` flag and properties of strings](https://github.com/tc39/proposal-regexp-v-flag). The proposal is at stage 3 and [has landed in v8 June 2022](https://v8.dev/features/regexp-v-flag). 

Given the extent of the changes in the proposal, implementing the `v` flag will likely require a new major version for regexpp, because the AST interface will change significantly.

### PR DESCRIPTION
**Pull request by ota-meshi**
### Overview

This PR adds support for v flag.

#### Add new AST nodes

- `ExpressionCharacterClass`
  If the character class has intersection or subtraction it will be wrapped in this node. E.g. `[a--b]`, `[a&&b]`,`[^a--b]`, `[^a&&b]`
- `ClassIntersection`
  It is an intersection node. E.g. `a&&b`
- `ClassSubtraction`
  It is a subtraction node. E.g. `a--b`
- `ClassStringDisjunction`
  It is `\p{...}` node. E.g. `\q{a|b}`
- `StringAlternative`
  It is `Alternative` like node in `ClassStringDisjunction`.

#### Change AST nodes

- CharacterClass
  - Add `unicodeSets` flag. true if the regex has the v flag. It had this because negation (`^`) behaves differently at runtime.
- CharacterSet (with `kind: "property"`)
  - Add `strings` flag. true if it `\p{}` with property of string (e.g. `Basic_Emoji`). It has no negation.

#### Change API

- The fourth argument of `parser.parsePattern` and `validator.validatePattern` has been changed from a boolean `uFlag` to an object with flags.
  This is because the object format is easier to use than specifying multiple flags in argument order. For backward compatibility, the old boolean value work as well.

---

close #80

### CODE REVIEW

**Comment by RunDevelopment** [comment]
Thank you @ota-meshi! I'll review this soon.

---

There is one thing I noticed by looking at the AST format: `Alternative`. I think that it's very confusing that `Alternative` is now either a `DisjunctionAlternative` or a `StringAlternative`. The 2 types of alternatives seem very different to me, so I think that combining them under `Alternative` doesn't make much sense. 

I also think that the new `Alternative` just isn't a useful type. In the entire AST definition, the `Alterantive` type is used 2 times, while `DisjunctionAlternative` is used 20 times and `StringAlternative` used 2 times. ``DisjunctionAlternative`` and `StringAlternative` aren't used together much.

So I think it would make sense to more clearly separate the new `StringAlternative`. I would keep the old `Alternative` definition and make a new type for `StringAlternative`.

**Comment by ota-meshi** [comment]
Good point. I think your idea makes sense. I will change the AST.

**Comment by ota-meshi** [comment]
I refactored this PR. Previously, a character string indicating the kind was returned from some consume functions and processed. However, this was inconsistent so we refactored the consume function to return a boolean.

https://github.com/eslint-community/regexpp/pull/82/commits/8d46d1456cb29f7517b1ae98d03f393608f3b018

**Comment by ota-meshi** [comment]
I refactored this PR. Changed MayContainStrings to handle using result. This follows a review comment in PR in Acorn.

https://github.com/eslint-community/regexpp/pull/82/commits/ffcaed597097baf5ab75535a75580121160dcd09

**Comment by ota-meshi** [comment]
@eslint-community/core-team @RunDevelopment 
Could you please check this PR if you are interested?
If no one responds, I'll merge and release this PR after next week.

**Review by aladdin-add — APPROVED** [review]
Not very familiar with this repo, but the test cases look good! :)

**Comment by ota-meshi** [comment]
Thank you for checking out this PR. I will merge this PR.

**Comment by ota-meshi** [comment]
Hi @RunDevelopment!
I invited you to the team. I would be happy if you accept it.

**Comment by RunDevelopment** [comment]
Joined. Thanks @ota-meshi!

**Pull request merged**
